// Auto-generated by NLS Refactor. Do not edit manually.
const { translate } = require('./nls_loader').default;

const nls_ts = {
  cache: {
    empty: {
      text: "cache.empty.text"
    },
    table: {
      title: "cache.table.title"
    },
    column: {
      src: {
        title: "cache.column.src.title"
      },
      dst: {
        title: "cache.column.dst.title"
      }
    },
    action: {
      title: "cache.action.title"
    }
  }
};

module.exports = { nls_ts, translate };